default:
	darnit-stringtable configuration ../bin/system.stz
	darnit-stringtable items ../bin/items.stz
	darnit-stringtable party ../bin/party.stz
	darnit-stringtable mapfile_table ../bin/maps.stz

clean:
	
